# EJERCICIO 1
Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

El primer paso va a ser importar la libreria y crear una lista.

import numpy as np

In [3]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

Ahora convierto la lista en un array de numpy para poder operar con la librería, al venir de una lista va a tener solo una dimesión. 

In [4]:
np.array(lista)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Lo guardo en un objeto.

In [5]:
arr = np.array(lista)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Compruebo el tipo para asegurarme que sea un array. 

In [7]:
type(arr)

numpy.ndarray

Comprobamos con el comando .ndim el número de dimensiones sobre nuestro array.

In [8]:
vector = arr
print(vector)
vector.ndim

[1 2 3 4 5 6 7 8 9]


1

In [9]:
print(arr)
arr.ndim


[1 2 3 4 5 6 7 8 9]


1

Realizamos el resumen estadístico básico:
* Media
* Mediana 
* Moda 
* Rango
* Desviación estándar